### ISSUE TITLE
Remove corp from link

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#72] opened 2022-05-25 20:57 UTC
Issue in /src/pages/implement/client-side/atjs/target-atjs-faq/target-atjs-faq.md

![image](https://user-images.githubusercontent.com/106278998/170365858-33f3ae2e-9a4e-474c-9f52-a31e7865f9fa.png)

**Comment by judy-kim** [comment] 2022-06-06 22:38
Closed -- dupe of [Issue 78](https://github.com/AdobeDocs/target-developers/issues/78), which was resolved across the repo. Thanks!

**Closed** 2022-06-06 22:38 UTC
