### ISSUE TITLE
Menu highlight need correction

### ISSUE THREAD

**Issue by bennet-roy** [AdobeDocs/target-developers#26] opened 2022-05-25 20:32 UTC
When a user is browsing the https://developer-stage.adobe.com/target/ page, the menu that gets highlighted is "Before you Implement", it should be Adobe Target Developer Guide

**Comment by judy-kim** [comment] 2022-06-20 22:00
This was due to us overriding the default IO site setting for the entire top nav -- a site setting which usually places a "[Products](https://developer-stage.adobe.com/apis/)" link in that "home" top nav location. We replaced "Products" with "[Adobe Target Developer Guide](https://developer-stage.adobe.com/target/)." The problem is that the menu highlighting behavior assumes that "Products" remains in the "home" position, and therefore highlights the first top nav item that occurs after the "home" link. When we forced the "home" link to in fact be the Adobe Target Developer Guide landing page, the site still highlighted the first top nav item that occurred after the new "home" link -- even though this highlighting was now incorrect.

Resolved by reverting to the site's default setting of having "Products" as the home link once again. This is not ideal; we may revisit this in the future to find a way to reinstate Adobe Target Developer Guide as our home link.

**Closed by judy-kim** 2022-06-20 22:00 UTC
