### ISSUE TITLE
Breadcrumb needs to begin with Adobe Target Developer Guide, not Products 

### ISSUE THREAD

**Issue by bennet-roy** [AdobeDocs/target-developers#44] opened 2022-05-25 20:42 UTC
Issue in /src/pages/before-administer/index.md

If you look at the breadcrumb, it begins with Products > Adobe Target Developer Guide and if someone clicks on the Products, they are taken out of the documentation portal. I believe we can begin the breadcrumb from Adobe Target Developer Guide

**Comment by judy-kim** [comment] 2022-06-13 21:51
Asking IO team for assistance

**Comment by judy-kim** [comment] 2022-06-16 14:36
Logged [DEVSITE-444](https://jira.corp.adobe.com/browse/DEVSITE-444)

**Comment by judy-kim** [comment] 2022-06-20 22:05
Logged a JIRA for the devsite team. However, note this is operating as intended. The breadcrumb path should make more sense now that the "home" link for the site has been reinstated as "[Products](https://developer-stage.adobe.com/apis/)" as well -- see Issue #26 -- so marking this as completed. Can reopen if/when we likewise revisit the home link issue described in Issue #26.

**Closed by judy-kim** 2022-06-20 22:05 UTC
