### ISSUE TITLE
Link goes to corp.adobe.com

### ISSUE THREAD

**Issue by mtalbot29** [AdobeDocs/target-developers#48] opened 2022-05-25 20:43 UTC
Issue in /src/pages/implement/mobile/prefetch-offer-content.md

Prefetch functionality is not supported for Auto-Allocate and Auto-Target traffic allocation methods, for Automated Personalization or Recommendations activity types, or for [recommendations offers within an A/B or XT activity](https://experienceleague.corp.adobe.com/docs/target/using/recommendations/recommendations-as-an-offer.html).

**Comment by judy-kim** [comment] 2022-06-13 17:42
Dupe of Issue #78. Fixed.

**Closed by judy-kim** 2022-06-13 17:42 UTC
