### ISSUE TITLE
Link for "How Adobe Target Works" references adobe corp page

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#63] opened 2022-05-25 20:53 UTC
Issue in /src/pages/before-implement/privacy/cookie-behavior.md

Steps to Reproduce: 
1. Go to https://developer-stage.adobe.com/target/before-implement/privacy/cookie-behavior/
2. Click [How Adobe Target Works](https://experienceleague.corp.adobe.com/docs/target/using/introduction/how-target-works.html)
3. Observe that internal page is referenced

**Comment by sgoffadobe** [comment] 2022-05-25 20:53
Also impacted is the link for [profile lifetime length](https://experienceleague.corp.adobe.com/docs/target/using/audiences/visitor-profiles/visitor-profile-lifetime.html)

**Comment by judy-kim** [comment] 2022-06-13 15:56
Dupe of Issue #78

**Closed by judy-kim** 2022-06-13 15:56 UTC
