### ISSUE TITLE
References to experience league corp pages

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#73] opened 2022-05-25 20:57 UTC
Issue in /src/pages/before-implement/privacy/apple-itp-2x.md

Steps to Reproduce:
1. Go to URL https://developer-stage.adobe.com/target/before-implement/privacy/apple-itp-2x/#is-my-current-implementation-of-target-impacted
2. Click on [profile scripts](https://experienceleague.corp.adobe.com/docs/target/using/audiences/visitor-profiles/profile-parameters.html) and [QA/Preview URLs](https://experienceleague.corp.adobe.com/docs/target/using/activities/activity-qa/activity-qa.html)
3. Observe corp page is displayed

**Comment by sgoffadobe** [comment] 2022-05-25 20:58
Also impacts https://developer-stage.adobe.com/target/before-implement/privacy/allowlist-edges/ --> [The edge network](https://experienceleague.corp.adobe.com/docs/target/using/introduction/how-target-works.html#concept_0AE2ED8E9DE64288A8B30FCBF1040934)

**Comment by judy-kim** [comment] 2022-06-06 22:37
Closed -- dupe of [Issue 78](https://github.com/AdobeDocs/target-developers/issues/78), which was resolved across the repo. Thanks!

**Closed by judy-kim** 2022-06-06 22:37 UTC
